[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#4a4a4a"
blue = "#709dd0"
cyan = "#71ced1"
green = "#b8bb26"
magenta = "#c792ea"
red = "#fb4934"
white = "#ffffff"
yellow = "#fabd2f"

[colors.cursor]
cursor = "#f9f5d7"
text = "#1D2021"

[colors.footer_bar]
background = "#d79921"
foreground = "#1D2021"

[colors.hints.end]
background = "#1D2021"
foreground = "#8ec07c"

[colors.hints.start]
background = "#1D2021"
foreground = "#d79921"

[colors.normal]
black = "#212121"
# blue = "#82aaff"
# blue = "#83a598"
blue = "#709dd0"
# cyan = "#89ddff"
# cyan = "#8ec07c"
cyan = "#71ced1"
# green = "#c3e88d"
green = "#b8bb26"
magenta = "#c792ea"
# magenta = "#d3869b"
# red = "#f07178"
red = "#fb4934"
# white = "#ffffff"
white = "#f9f5d7"
# yellow = "#ffcb6b"
yellow = "#fabd2f"

[colors.primary]
background = "#1D2021"
foreground = "#f9f5d7"

[colors.search.focused_match]
background = "#f9f5d7"
foreground = "#1D2021"

[colors.search.matches]
background = "#d79921"
foreground = "#1D2021"

[colors.selection]
background = "#f9f5d7"
text = "#1D2021"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

